name: factup

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  proxy:
    container_name: factup_proxy
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./packages/frontend/dist:/usr/share/nginx/html
      - ./docker/proxy/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - factup_network
    depends_on:
      backend:
        condition: service_started



  postgres:
    container_name: factup_postgres
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=factup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "factup"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    ports:
      - 5432:5432
    volumes:
      - factup_postgres:/var/lib/postgresql/data
    networks:
      - factup_network



  migrator:
    container_name: factup_migrator
    build:
      context: ./packages/migrator
      dockerfile: Dockerfile
    environment:
      - MIGRATOR_POSTGRES_CONNECTION_URL=postgresql://postgres:postgres@postgres:5432/factup?sslmode=disable
    volumes:
      - ./packages/migrator/migrations:/app/migrations:ro
    networks:
      - factup_network
    depends_on:
      postgres:
        condition: service_healthy



  backend:
    container_name: factup_backend
    restart: always
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
      - BACKEND_POSTGRES_CONNECTION_URL=postgresql://postgres:postgres@postgres:5432/factup?sslmode=disable
    env_file:
      - .env
    volumes:
      - ./docker/volumes/images:/app/images
    networks:
      - factup_network
    depends_on:
      postgres:
        condition: service_healthy



  dcmodder:
    container_name: factup_dcmodder
    restart: always
    build:
      context: ./packages/dcmodder
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - factup_network
    depends_on:
      backend:
        condition: service_started



volumes:
  factup_postgres:



networks:
  factup_network:
    driver: bridge

