// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package orm

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32
	UserID    int32
	Body      string
	Source    pgtype.Text
	ImagePath pgtype.Text
}

type User struct {
	ID          int32
	Email       string
	DisplayName string
}

type UserInteraction struct {
	ID     int32
	PostID int32
	UserID int32
	Score  int16
}
