// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package orm

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32              `json:"id"`
	Type      string             `json:"type"`
	UserID    int32              `json:"userId"`
	Body      string             `json:"body"`
	Source    pgtype.Text        `json:"source"`
	ImagePath pgtype.Text        `json:"imagePath"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID          int32              `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"displayName"`
	ImagePath   pgtype.Text        `json:"imagePath"`
	Category    string             `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	Banned      bool               `json:"banned"`
}

type UserBot struct {
	ID     int32  `json:"id"`
	UserID int32  `json:"userId"`
	Name   string `json:"name"`
	Secret string `json:"secret"`
}

type UserInteraction struct {
	ID     int32 `json:"id"`
	PostID int32 `json:"postId"`
	UserID int32 `json:"userId"`
	Score  int16 `json:"score"`
}
